/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/Building.gltf');
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Jazz.geometry} material={materials.Neon_Emit} />
      <group
        position={[-0.95, 1.21, 2.77]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.29}
      >
        <mesh
          geometry={nodes.Text003_1.geometry}
          material={materials.neoner_Pink}
        />
        <mesh
          geometry={nodes.Text003_2.geometry}
          material={materials.neoner_Blue}
        />
      </group>
      <mesh geometry={nodes.Text003.geometry} material={materials.Neon_Emit} />
      <mesh geometry={nodes.Plane001.geometry} material={materials.Emit_Blue} />
      <mesh geometry={nodes.Ground.geometry} material={materials.Street} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.House} />
      <mesh geometry={nodes.Cube001_1.geometry} material={materials.Metal_3} />
      <mesh
        geometry={nodes.Cube001_2.geometry}
        material={materials.Emit_Pink}
      />
      <mesh geometry={nodes.Cube001_3.geometry} material={materials.Street} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.Garage} />
      <mesh geometry={nodes.Cube003_1.geometry} material={materials.Garage_2} />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={materials['Material.001']}
      />
      <mesh
        geometry={nodes.Cube004_1.geometry}
        material={materials.Emit_Pink}
      />
      <mesh geometry={nodes.Cube004_2.geometry} material={materials.Metal_2} />
      <mesh geometry={nodes.Cube004_3.geometry} material={materials.White} />
      <mesh
        geometry={nodes.Plane_1.geometry}
        material={materials.Window_Emit}
      />
      <mesh
        geometry={nodes.Plane_2.geometry}
        material={materials.Emit_Window}
      />
      <mesh
        geometry={nodes.Plane_3.geometry}
        material={materials.Window_Glass}
      />
      <mesh geometry={nodes.Rollo.geometry} material={materials.Rollos} />
      <mesh
        geometry={nodes.Support.geometry}
        material={materials.Metal_2}
        position={[3.69, 0.98, 0.4]}
      />
      <mesh
        geometry={nodes.Metal_Tubes.geometry}
        material={materials.Metal_2}
        position={[3.69, 0.98, 0.4]}
      />
      <group position={[3.69, 0.98, 0.4]}>
        <mesh geometry={nodes.Cube012.geometry} material={materials.House} />
        <mesh geometry={nodes.Cube012_1.geometry} material={materials.Street} />
      </group>
      <mesh
        geometry={nodes.Rain_Tube_2.geometry}
        material={materials.Copper}
        position={[3.69, 0.98, 0.4]}
      />
      <mesh
        geometry={nodes.Rain_Tube_1.geometry}
        material={materials.Copper}
        position={[3.69, 0.98, 0.4]}
      />
      <mesh
        geometry={nodes.Carton.geometry}
        material={materials.Carton}
        position={[3.69, 0.98, 0.4]}
      />
      <mesh
        geometry={nodes.Rubbish.geometry}
        material={materials.Rubbish}
        position={[3.69, 0.98, 0.4]}
      />
      <group position={[3.69, 0.98, 0.4]}>
        <mesh geometry={nodes.Plane003.geometry} material={materials.Cloth_5} />
        <mesh geometry={nodes.Plane003_1.geometry} material={materials.Grau} />
      </group>
      <mesh
        geometry={nodes.Cabel_2.geometry}
        material={materials.Cabel}
        position={[3.69, 0.98, 0.4]}
      />
      <group position={[3.69, 0.98, 0.4]}>
        <mesh geometry={nodes.Cube019.geometry} material={materials.Garage} />
        <mesh geometry={nodes.Cube019_1.geometry} material={materials.Door} />
      </group>
      <group position={[3.69, 0.98, 0.4]}>
        <mesh
          geometry={nodes.Cube020.geometry}
          material={materials.Electro_Box_2}
        />
        <mesh geometry={nodes.Cube020_1.geometry} material={materials.Emit} />
        <mesh
          geometry={nodes.Cube020_2.geometry}
          material={materials.Electro_Box_1}
        />
        <mesh
          geometry={nodes.Cube020_3.geometry}
          material={materials.Electro_Box_3}
        />
        <mesh
          geometry={nodes.Cube020_4.geometry}
          material={materials.Metal_2}
        />
      </group>
      <mesh
        geometry={nodes['24'].geometry}
        material={materials.Metal_1}
        position={[0.62, 1.13, 1.07]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.26}
      />
      <group position={[3.69, 0.98, 0.4]}>
        <mesh geometry={nodes.Cube024.geometry} material={materials.White} />
        <mesh
          geometry={nodes.Cube024_1.geometry}
          material={materials['Material.003']}
        />
      </group>
      <group position={[0.66, 4.41, 0.62]}>
        <mesh geometry={nodes.Cube026.geometry} material={materials.Metal_2} />
        <mesh geometry={nodes.Cube026_1.geometry} material={materials.White} />
      </group>
      <mesh
        geometry={nodes.Cabel_3.geometry}
        material={materials.Metal_2}
        position={[2.54, 0, 2.5]}
      />
      <group position={[3.69, 0.98, 0.4]}>
        <mesh
          geometry={nodes.Cylinder002.geometry}
          material={materials.Cabel}
        />
        <mesh
          geometry={nodes.Cylinder002_1.geometry}
          material={materials.Neon_Emit}
        />
      </group>
      <group position={[-0.28, 3.15, 1.01]}>
        <mesh geometry={nodes.Cube028.geometry} material={materials.Cloth_5} />
        <mesh geometry={nodes.Cube028_1.geometry} material={materials.Wood} />
      </group>
      <mesh
        geometry={nodes.Cabel.geometry}
        material={materials.Cabel}
        position={[-1.63, 0.62, 0.51]}
        rotation={[0, 0.23, 0]}
      />
      <group position={[0.07, 3.17, 1.11]}>
        <mesh geometry={nodes.Plane007.geometry} material={materials.Cloth_1} />
        <mesh
          geometry={nodes.Plane007_1.geometry}
          material={materials.Cloth_2}
        />
        <mesh
          geometry={nodes.Plane007_2.geometry}
          material={materials.Cloth_3}
        />
        <mesh
          geometry={nodes.Plane007_3.geometry}
          material={materials.Cloth_4}
        />
      </group>
      <mesh
        geometry={nodes.Beer.geometry}
        material={materials.Beer}
        position={[0.07, 3.17, 1.11]}
      />
      <mesh
        geometry={nodes.Stair.geometry}
        material={materials.Metal_2}
        position={[2.23, 1.15, -0.82]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.58}
      />
      <group
        position={[2.25, 1.25, -0.82]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.58}
      >
        <mesh geometry={nodes.Cube014.geometry} material={materials.Metal_1} />
        <mesh
          geometry={nodes.Cube014_1.geometry}
          material={materials.Metal_2}
        />
      </group>
      <mesh
        geometry={nodes.Stair_Tube_B.geometry}
        material={materials.Metal_1}
        position={[2.23, 1.15, -0.82]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.58}
      />
      <mesh
        geometry={nodes.Stair_Tubes_Small.geometry}
        material={materials.Metal_2}
        position={[2.23, 1.15, -0.82]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.58}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials.neoner_light}
        position={[-0.82, 1.35, 3.91]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.16}
      />
    </group>
  );
}

useGLTF.preload('/Building.gltf');
